sudo: true
language: cpp
dist: trusty

matrix:
  include:
  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-8
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8', 'libboost-all-dev']

  - os: linux
    compiler: clang
    env:
      - COMPILER=clang++-6.0
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
        packages: ['g++-8', 'clang-6.0', 'libboost-all-dev']

  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-8
      - CC=gcc8
      - CONAN_GCC_VERSIONS=8
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8', 'cmake']
    install:
      - sudo pip install conan conan-package-tools
    before_script:
      - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 50
      - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 50
    script:
      - python .conan/build.py

  - os: osx
    osx_image: xcode9.4

  - os: osx
    osx_image: xcode10
    
before_install:
    # libpcre2-dev
  - |
     if [[ (-x $(which brew)) ]]; then
       brew update
       brew install pcre2
     else
       sudo add-apt-repository -y ppa:sergey-dryabzhinsky/packages
       sudo apt-get update -qq
       sudo apt-get install -qq libpcre2-dev
     fi

install:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - uname -a
  - $CXX --version
script:
  - make
