sudo: false
language: cpp
compiler:
  - clang
addons:
  apt:
    sources:
    - llvm-toolchain-precise-5.0
    packages:
    - clang
install:
- "[ $CXX = clang++ ] && export CXX=clang++ || true"
script:
  - make